language: node_js
dist: xenial
node_js:
  - "10"
cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - /^@here\//

# upgrade yarn to a more recent version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: "Build & test"
      script: |
        set -ex
        yarn test
